name: chef_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Core & UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1 # Added for Cairo/Tajawal fonts

  # State Management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^15.1.1

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  firebase_core_platform_interface: ^5.4.0

  # Localization
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # Video & Image
  video_player: ^2.8.6 # Added for video playback
  image_picker: ^1.1.2 # Added for video/image uploads
  # chewie: ^1.7.5 # Optional: For video UI controls, consider if needed

  # Location & Permissions
  geolocator: ^12.0.0 # Added for location services
  permission_handler: ^11.3.1 # Added for handling permissions

  # Payments
  flutter_stripe: ^10.2.0 # Added for payment processing

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

