// File generated by Manus. Do not edit.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import "firebase_options.dart";
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "you can reconfigure this by running the FlutterFire CLI again.",
        );
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not supported for this platform.",
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc0siuSc33Ocs3A5ex6INUbQRAG8L8djQ',
    appId: '1:576853380936:android:069b19ccb760a9b848ed7d',
    messagingSenderId: '576853380936',
    projectId: 'chefapp-3f03e',
    storageBucket: 'chefapp-3f03e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANfp4bcGJc8wB0b3EO9PErCxjT8rFmcvs',
    appId: '1:576853380936:ios:f1d4b9c4462b38c048ed7d',
    messagingSenderId: '576853380936',
    projectId: 'chefapp-3f03e',
    storageBucket: 'chefapp-3f03e.firebasestorage.app',
    iosBundleId: 'com.example.chefApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClfmBX8qcYLAY53eE9A0wPtAvGRmhqR_o',
    appId: '1:576853380936:web:c63419de59acfbac48ed7d',
    messagingSenderId: '576853380936',
    projectId: 'chefapp-3f03e',
    authDomain: 'chefapp-3f03e.firebaseapp.com',
    storageBucket: 'chefapp-3f03e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANfp4bcGJc8wB0b3EO9PErCxjT8rFmcvs',
    appId: '1:576853380936:ios:f1d4b9c4462b38c048ed7d',
    messagingSenderId: '576853380936',
    projectId: 'chefapp-3f03e',
    storageBucket: 'chefapp-3f03e.firebasestorage.app',
    iosBundleId: 'com.example.chefApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClfmBX8qcYLAY53eE9A0wPtAvGRmhqR_o',
    appId: '1:576853380936:web:d875cfa4cc79171348ed7d',
    messagingSenderId: '576853380936',
    projectId: 'chefapp-3f03e',
    authDomain: 'chefapp-3f03e.firebaseapp.com',
    storageBucket: 'chefapp-3f03e.firebasestorage.app',
  );

}
